export const baseHeader = {
  Accept: "*/*",
  "Accept-Language": "en-GB,en;q=0.9,en-US;q=0.8,id;q=0.7",
  Connection: "keep-alive",
  "Content-Type": "application/json",
  Origin: "https://agents.testnet.gokite.ai",
  Referer: "https://agents.testnet.gokite.ai/",
  "Sec-Fetch-Dest": "empty",
  "Sec-Fetch-Mode": "cors",
  "Sec-Fetch-Site": "cross-site",
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36 Edg/133.0.0.0",
  "sec-ch-ua": '"Not(A:Brand";v="99", "Microsoft Edge";v="133", "Chromium";v="133"',
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": '"Windows"',
};
