export const questions = {
  "Kite AI Assistant": [
    "What is the purpose of Kite AI in coding workflows?",
    "How does Kite AI simplify code suggestions?",
    "What are the benefits of Kite AI for software developers?",
    "Can Kite AI assist with debugging code more efficiently?",
    "How does Kite AI differ from other similar tools?",
    "Can you explain the real-time capabilities of Kite AI?",
    "What is the role of AI in Kite AI's advanced features?",
    "What feedback mechanisms improve Kite AI performance?",
    "How does Kite AI ensure privacy in code recommendations?",
    "What are the common challenges solved by Kite AI?",
    "How can Kite AI help developers write more efficient code?",
    "What programming languages does Kite AI support?",
    "How does Kite AI's autocomplete differ from others?",
    "What are the steps to integrate Kite AI into existing projects?",
    "Can Kite AI assist with refactoring complex codebases?",
    "What is the future scope of Kite AI technology?",
    "How does Kite AI contribute to open-source development?",
    "What is Kite AI's approach to handling large projects?",
    "How does Kite AI help in learning new programming languages?",
    "Can you explain the impact of Kite AI in reducing coding errors?",
  ],
  "Crypto Price Assistant": [
    "What factors influence Bitcoin's market performance?",
    "How is Ethereum trending compared to other altcoins?",
    "Can you provide the latest sentiment analysis on Dogecoin?",
    "What are the top cryptocurrencies to watch this week?",
    "How do global events affect cryptocurrency prices?",
    "What is the historical price trend of XRP in the last year?",
    "How can one interpret RSI (Relative Strength Index) for crypto?",
    "What are the recent gains and losses for Litecoin?",
    "Can you summarize the 24-hour trading volume of Tether?",
    "How does Shiba Inu's performance compare to its competitors?",
    "What role does social media play in crypto price fluctuations?",
    "How do seasonal trends affect cryptocurrency markets?",
    "What is the importance of trading volume in crypto analysis?",
    "How do stablecoins help in managing market volatility?",
    "How can one analyze historical price patterns of altcoins?",
    "What is the role of institutional investors in crypto markets?",
    "What impact does hash rate have on Bitcoin's price?",
    "How do DeFi protocols influence cryptocurrency prices?",
    "Can price prediction tools reliably forecast crypto trends?",
    "What metrics indicate a crypto's market health?",
  ],
  "Transaction Analyzer": [
    "What is the purpose of transaction analysis in crypto?",
    "How can blockchain explorers be used to track transactions?",
    "What are the top tools for transaction fee estimation?",
    "How does analyzing gas fees benefit crypto traders?",
    "What patterns should I look for in suspicious transactions?",
    "How do transaction delays impact blockchain performance?",
    "Can transaction analysis predict market trends?",
    "What metrics are important in evaluating transaction success?",
    "How does transaction analysis help in fraud detection?",
    "What insights can be gained from analyzing wallet activities?",
    "What are common mistakes in transaction processing?",
    "How does transaction volume impact blockchain scalability?",
    "Can transaction analysis identify arbitrage opportunities?",
    "What role do validators play in ensuring transaction integrity?",
    "How can one reduce transaction costs on Ethereum?",
    "What are the benefits of analyzing NFT transactions?",
    "How does transaction analysis help improve DeFi platforms?",
    "How can spam transactions be identified and mitigated?",
    "What are the factors affecting transaction throughput?",
    "How does transaction batching improve efficiency?",
  ],
};
